name: Intro toCI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      
      - name: setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: install depencies
        run: pnpm install

      - name: build
        run: pnpm run build
      

          